import { NextIntlClientProvider, useMessages } from "next-intl";
import { ReactNode } from "react";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import NavBar from "@/components/nav-bar";
import AuthProvider from "@/components/auth-provider";

type Props = {
  children: ReactNode;
  params: { locale: string };
  auth: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Saas Template",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function LocaleLayout({ children, params: { locale } }: Props) {
  // Receive messages provided in `i18n.ts`
  const messages = useMessages();
  // console.log("layout " + JSON.stringify(messages));

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NavBar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
